### ISSUE TITLE
Require vector logo for Cowork Niagara

### ISSUE THREAD

**Issue by knicklabs** [softwareniagara/softwareniagara.com#20]
@adam12 I would like to add Cowork Niagara and Jetbrains to the supporters section of the new site. Do you have a vector version of the Cowork Niagara logo that you can supply?

**Comment by adam12** [comment]
Give this one a go:

https://www.dropbox.com/s/cvub7ph4nop4gwf/1color%20logo%20vertical.svg?dl=0

**Comment by knicklabs** [comment]
Perfect. Thanks!
