### ISSUE TITLE
Custom domain cleared after deploy

### ISSUE THREAD

**Issue by knicklabs** [softwareniagara/softwareniagara.com#29]
After every deploy to GitHub pages the custom domain field in the GH Pages settings is being cleared resulting in the site being down until the value is manually restored.

**Comment by adam12** [comment]
Do we need to have a `CNAME` file? I noticed it was removed.

**Comment by knicklabs** [comment]
I did not think it was necessary anymore since I didn't see mention of it in the docs and they introduced this new setting. But perhaps it is.

**Comment by adam12** [comment]
Strange..

**Comment by knicklabs** [comment]
Yep. Added it anyway and redeployed to test. The custom domain setting was still cleared but the cname still works. I'm satisfied with that. As long as it doesn't break on deploy.

**Comment by knicklabs** [comment]
Re-opening this issue. The CNAME file does not work.

**Comment by adam12** [comment]
Does it need to be in `source/`?

**Comment by knicklabs** [comment]
Yes >:| 

And with that there, the setting is sticking too.
