### ISSUE TITLE
yarn or npm?

### ISSUE THREAD

**Issue by RichAyotte** [softwareniagara/softwareniagara.com#4]
We have both `yarn.lock` and `package-lock.json` in the repo which is a bit confusing and could potentially cause problems with package dependencies. Either one is fine but I think we should pick one and delete the other to avoid confusion. Thoughts?

**Comment by knicklabs** [comment]
I believe Gatsby installed with both. I think we should ditch `yarn.lock` since `yarn` is not the default and I don't think it offers anything compelling over `npm` anymore.
